### ISSUE TITLE
BitBadges API

### ISSUE THREAD

**Issue by trevormil** [cloutapis/cloutapis#33]
Would love to add the BitBadges API here. It's already up and running. I will neaten up the documentation soon but what steps should I take to add it here? PR? Send documentation to someone?

**Comment by chrismaddern** [comment]
You're welcome to take either approach! (Sorry for the delay) @trevormil

* PRs welcome
* If you outline the functionality here first, either we can help or at the very least make sure that we're all on the same page before it gets going
* If you just outline here, I can probably find some time to give it a go too 😊
